# Generated by Django 3.1.7 on 2021-04-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210409_2309'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='organization.organization')),
            ],
            options={
                'db_table': 'raw_materials',
                'ordering': ['-created_at'],
                'permissions': [('supplier_can_create', 'Supplier can create raw material'), ('supplier_can_update', 'Supplier can update raw material'), ('supplier_can_delete', 'Supplier can delete raw material'), ('supplier_can_view', 'Supplier can view raw material'), ('pharma_can_view', 'Pharmaceutical can view raw material'), ('pharma_can_view_list', 'Pharmaceutical can view raw material list')],
            },
        ),
    ]
