# Generated by Django 3.1.7 on 2021-05-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_batch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'permissions': [('pharma_can_create', 'Pharma can create batch'), ('pharma_can_update', 'Pharma can update batch'), ('pharma_can_view', 'Pharma can view batch'), ('retailer_can_order', 'Retailer can order batch'), ('retailer_can_view', 'Retailer can view batch')]},
        ),
    ]
