# Generated by Django 3.1.7 on 2021-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210516_0203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['created_at'], 'permissions': [('pharma_can_create_batch', 'Pharma can create batch'), ('pharma_can_update_batch', 'Pharma can update batch'), ('pharma_can_view_batch', 'Pharma can view batch'), ('retailer_can_order_batch', 'Retailer can order batch'), ('retailer_can_view_batch', 'Retailer can view batch')]},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
