# Generated by Django 3.1.7 on 2021-05-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210525_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('pharma_can_create', 'Pharma can create product'), ('pharma_can_update', 'Pharma can update product'), ('pharma_can_delete', 'Pharma_can_delete_product'), ('pharma_can_view', 'Pharma can view product'), ('pharma_can_view_list', 'Pharma can view product list'), ('retailer_can_view_list', 'Retailer can view list'), ('retailer_can_view_detail', 'Retailer can view detail')]},
        ),
    ]
