# Generated by Django 3.1.7 on 2021-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
