# Generated by Django 3.1.7 on 2021-04-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210404_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('producer', 'Producer'), ('seller', 'Seller')], max_length=20),
        ),
    ]
