# Generated by Django 3.1.7 on 2021-04-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210406_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('pharmaceutical', 'Pharmaceutical'), ('supplier', 'Supplier'), ('retailer', 'Retailer')], max_length=20),
        ),
    ]
