# Generated by Django 3.1.7 on 2021-04-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210409_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('seller_order_list', 'Can view order request list'), ('pharma_order_list', 'Can view order list made by pharma')]},
        ),
    ]
