# Generated by Django 3.1.7 on 2021-04-11 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_auto_20210409_2309'),
        ('inventory', '0005_auto_20210411_0306'),
        ('order', '0004_auto_20210410_0514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='ProductOrder',
        ),
        migrations.AlterModelTable(
            name='productorder',
            table='product_orders',
        ),
    ]
