# Generated by Django 3.1.7 on 2021-04-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210412_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawmaterialorder',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
