# Generated by Django 3.1.7 on 2021-04-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210412_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterialorder',
            options={'ordering': ['-created_at'], 'permissions': [('pharma_can_create_order_raw_material', 'Pharma can create order for raw material'), ('pharma_can_cancel_order_raw_material', 'Pharma can cancel order for raw material'), ('pharma_can_view_ordered_raw_material', 'Pharma can view ordered raw material'), ('supplier_can_edit_order_raw_material', 'Supplier can edit order for raw material'), ('supplier_can_fulfill_order_raw_material', 'Supplier can fulfill order for raw material'), ('supplier_can_reject_order_raw_material', 'Supplier can reject order for raw material'), ('supplier_can_view_order_raw_material_list', 'Supplier can view order list for raw material')]},
        ),
    ]
