# Generated by Django 3.1.7 on 2021-05-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210525_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['-created_at'], 'permissions': [('supplier_order_list', 'Can view order request list for the supplier'), ('pharma_order_list', 'Can view order list made by pharma'), ('retailer_order_list', 'Can view order list made by retailer'), ('retailer_create_order', 'Retailer can create order')]},
        ),
    ]
