# Generated by Django 3.1.7 on 2021-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210525_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
